// Unique local content for every suburb Linda serves. Loaded by Suburb.dc.html.
window.SUBURBS_DATA = {
  regions: {
    macarthur: "Campbelltown & Macarthur",
    camden: "Camden & the South West growth corridor",
    liverpool: "Liverpool & surrounds",
    georges: "Georges River & Menai district"
  },
  list: [
    // ---------------- CAMPBELLTOWN & MACARTHUR ----------------
    { slug:"macquarie-fields", name:"Macquarie Fields", postcode:"2564", region:"macarthur",
      lead:"Macquarie Fields is one of the suburbs I most often marry couples in — just minutes from my Macquarie Links base.",
      about:"Macquarie Fields is a settled, family-oriented pocket of the Macarthur region, threaded by the Georges River parklands and known for its quiet residential streets and strong community feel. It sits on the T8 line, which makes it easy for guests travelling out from central Sydney, and its mix of established homes and green reserves gives couples plenty of relaxed, unpretentious settings for a wedding.",
      ceremony:"Most couples here marry in a family backyard, at a local reserve along the Georges River, or at a nearby function venue, then celebrate close to home. Based just up the road in Macquarie Links, I can meet you in person easily, visit your ceremony spot beforehand, and arrive early on the day with my own PA so every guest hears your vows clearly.",
      venues:[{name:"Georges River parklands",note:"leafy riverside reserves for relaxed outdoor vows"},{name:"Family backyards",note:"the most popular choice — intimate and cost-effective"},{name:"Local community & function halls",note:"an easy wet-weather backup close to home"}],
      tip:"Weekend traffic through Macquarie Fields is light, but if guests are coming from the city, the train station is a genuinely convenient meeting point — worth noting on your invitations.",
      neighbours:["ingleburn","glenfield","minto","st-andrews","macquarie-links"] },

    { slug:"ingleburn", name:"Ingleburn", postcode:"2565", region:"macarthur",
      lead:"Ingleburn blends heritage charm with a growing, diverse community — a lovely backdrop for a personal ceremony.",
      about:"Ingleburn grew around its historic railway village and still keeps a distinct main-street character, with the Ingleburn Reserve and nearby bushland offering green space right in the heart of the suburb. It's one of the more culturally diverse pockets of the Macarthur region, which means many of the weddings I conduct here beautifully blend traditions and languages.",
      ceremony:"Ingleburn couples often marry at a reserve, a reception venue along the highway, or at home, with a strong appetite for multicultural ceremonies that honour two families. I regularly weave in bilingual elements, Christian blessings and cultural rituals so every guest feels part of the day.",
      venues:[{name:"Ingleburn Reserve",note:"open lawns and shade trees for an outdoor ceremony"},{name:"Local reception venues",note:"popular for combined ceremony-and-celebration days"},{name:"At-home ceremonies",note:"warm and personal, with family close by"}],
      tip:"Ingleburn's older streets can have limited parking near reserves — let elderly guests know the closest drop-off point so nobody has to walk far in their finery.",
      neighbours:["macquarie-fields","minto","glenfield","denham-court","bow-bowing"] },

    { slug:"minto", name:"Minto", postcode:"2566", region:"macarthur",
      lead:"Minto's renewed streets and open reserves make it an easy, welcoming place to marry.",
      about:"Minto has been substantially renewed over the past decade, giving it a fresh, green residential feel with new parks and community spaces alongside its established areas. Central to the Macarthur region and close to both Campbelltown and Ingleburn, it's a practical base for couples wanting family and guests within an easy drive.",
      ceremony:"Backyard and reserve ceremonies are common in Minto, often followed by a reception a short drive away in Campbelltown or Ingleburn. I handle the full legal side and design a ceremony that suits the setting, whether that's a relaxed park gathering or a more formal event.",
      venues:[{name:"Minto's renewed parklands",note:"modern, open reserves ideal for a garden-style ceremony"},{name:"Local sporting & community clubs",note:"comfortable, weatherproof spaces for larger guest lists"},{name:"Family homes",note:"intimate ceremonies with everyone nearby"}],
      tip:"Minto's newer parks are lovely but exposed — for a summer wedding, an early-morning or late-afternoon ceremony keeps everyone comfortable and the photos glowing.",
      neighbours:["ingleburn","macquarie-fields","raby","eagle-vale","leumeah","bow-bowing"] },

    { slug:"glenfield", name:"Glenfield", postcode:"2167", region:"macarthur",
      lead:"Glenfield sits at the gateway of the Macarthur region, handy to both Liverpool and Campbelltown.",
      about:"Glenfield is a well-connected suburb straddling the line between South West Sydney and Macarthur, with the Georges River and Casula Powerhouse precinct not far away. Its transport links and rapid residential growth make it a convenient meeting point for families spread across greater Sydney.",
      ceremony:"Couples in Glenfield tend to marry at riverside reserves, nearby function centres, or at home, and value a celebrant who can travel easily between the family's various suburbs. I'm just minutes away and know the local roads well.",
      venues:[{name:"Georges River reserves",note:"green, water-touched settings on the suburb's edge"},{name:"Nearby Casula precinct venues",note:"a short hop for a ceremony-and-reception combination"},{name:"Backyard ceremonies",note:"relaxed and personal"}],
      tip:"Glenfield's proximity to the motorway means guests from the city arrive quickly — but build in a few buffer minutes on a Saturday when the M5 is busy.",
      neighbours:["macquarie-fields","ingleburn","casula","prestons","macquarie-links"] },

    { slug:"campbelltown", name:"Campbelltown", postcode:"2560", region:"macarthur",
      lead:"As the heart of the Macarthur region, Campbelltown offers the widest choice of wedding venues in my service area.",
      about:"Campbelltown is the commercial and cultural centre of the Macarthur region, with a rich colonial history, established gardens and a full range of reception venues, clubs and hotels. Its scale means couples here can choose anything from an intimate garden ceremony to a large, multicultural celebration under one roof.",
      ceremony:"Because Campbelltown has so many function venues, many couples hold the ceremony and reception at the same location. I work seamlessly with venue coordinators, arrive early to set up, and keep the timing calm and on track so your day flows.",
      venues:[{name:"Established reception venues & clubs",note:"all-in-one ceremony and celebration spaces"},{name:"Historic gardens & reserves",note:"classic, elegant outdoor backdrops"},{name:"Hotels & function centres",note:"ideal for larger guest lists and wet-weather certainty"}],
      tip:"Campbelltown venues book out well ahead in peak season — secure your celebrant and venue together, 9–12 months out, to lock in your preferred Saturday.",
      neighbours:["leumeah","ambarvale","bradbury","minto"] },

    { slug:"leumeah", name:"Leumeah", postcode:"2560", region:"macarthur",
      lead:"Leumeah pairs easy access with a relaxed, community atmosphere for your ceremony.",
      about:"Leumeah sits just north of Campbelltown's centre, with its own railway station, sporting grounds and a comfortable suburban character. It's a practical, unfussy choice for couples who want to stay close to Campbelltown's venues while keeping things a little more low-key.",
      ceremony:"Ceremonies in Leumeah are often held at local clubs, sporting venues or family homes, with the reception nearby. I bring everything needed for a polished ceremony and take care of the paperwork from start to finish.",
      venues:[{name:"Sporting & leagues clubs",note:"spacious, weatherproof and well-serviced"},{name:"Local reserves",note:"simple, green settings for an outdoor exchange"},{name:"At-home ceremonies",note:"personal and budget-friendly"}],
      tip:"Leumeah station is right in the middle of the suburb — a handy landmark for directing guests who are catching the train from the city.",
      neighbours:["campbelltown","minto","bradbury","ambarvale"] },

    { slug:"ambarvale", name:"Ambarvale", postcode:"2560", region:"macarthur",
      lead:"Ambarvale's leafy streets and nearby bushland lend a natural softness to outdoor ceremonies.",
      about:"Ambarvale is a quiet residential suburb on the southern edge of Campbelltown, bordered by bushland reserves and rolling green space. Its calm, established feel makes it popular with families who've lived in the area for years and want to marry close to home.",
      ceremony:"Backyard and reserve ceremonies suit Ambarvale well, often with the reception held a short drive into Campbelltown. I design the ceremony around your setting and make sure the legal requirements are handled correctly and early.",
      venues:[{name:"Bushland reserves",note:"natural, green backdrops on the suburb's fringe"},{name:"Family backyards",note:"intimate ceremonies among familiar surrounds"},{name:"Nearby Campbelltown venues",note:"an easy move for the celebration"}],
      tip:"The bushland edges around Ambarvale are beautiful but can be uneven underfoot — check the ground for heels and wheelchairs, and I'll position everything so it's accessible.",
      neighbours:["campbelltown","bradbury","rosemeadow","leumeah"] },

    { slug:"bradbury", name:"Bradbury", postcode:"2560", region:"macarthur",
      lead:"Bradbury enjoys elevated outlooks and easy access to Campbelltown's full range of venues.",
      about:"Perched on rising ground south of Campbelltown, Bradbury offers some of the better views in the area along with a settled, family suburban feel. It's close enough to Campbelltown's venues to be convenient, yet quiet enough for a relaxed at-home celebration.",
      ceremony:"Bradbury couples often marry at home or at a nearby reserve, then celebrate in Campbelltown. I'm happy to visit beforehand to plan where you'll stand for the best light and outlook.",
      venues:[{name:"Elevated backyard ceremonies",note:"lovely outlooks for photos"},{name:"Local reserves & parks",note:"green, open settings"},{name:"Campbelltown reception venues",note:"a short drive for the party"}],
      tip:"Bradbury's higher streets can catch a breeze — bring a few weights for the arbour and any lightweight décor, and I'll site the ceremony to shelter you from the wind.",
      neighbours:["campbelltown","ambarvale","leumeah","rosemeadow"] },

    { slug:"raby", name:"Raby", postcode:"2566", region:"macarthur",
      lead:"Raby's spacious blocks and green streets suit generous, family-focused ceremonies.",
      about:"Raby is a comfortable residential suburb known for its larger blocks, parks and quiet cul-de-sacs. That extra space makes it a favourite for at-home weddings where families can gather in the garden without feeling cramped.",
      ceremony:"Backyard ceremonies shine in Raby, often for larger family gatherings. I bring a full PA so vows carry across a big garden, and I handle every legal detail so you can simply enjoy the day.",
      venues:[{name:"Large family backyards",note:"room for a real garden wedding at home"},{name:"Neighbourhood parks",note:"open green space for outdoor vows"},{name:"Nearby Eagle Vale & Minto venues",note:"handy for the reception"}],
      tip:"Raby's generous gardens are perfect for a ceremony — just plan shade for guests in summer, whether that's a marquee, umbrellas or a well-placed tree.",
      neighbours:["minto","eagle-vale","kearns","st-andrews"] },

    { slug:"eagle-vale", name:"Eagle Vale", postcode:"2558", region:"macarthur",
      lead:"Eagle Vale offers convenient local amenities and green reserves for a relaxed wedding.",
      about:"Eagle Vale is a well-established suburb with its own local centre, schools and parks, sitting comfortably within the Macarthur region. Its practical, family-friendly layout makes it easy for guests to find their way and for couples to keep the day close to home.",
      ceremony:"Ceremonies here are typically held in backyards or nearby reserves, with receptions at local clubs. I coordinate the timing and legalities and make sure your ceremony feels personal, not procedural.",
      venues:[{name:"Local reserves",note:"green, accessible outdoor settings"},{name:"Family homes",note:"warm, intimate ceremonies"},{name:"Nearby clubs",note:"comfortable indoor celebration spaces"}],
      tip:"Eagle Vale's local shops make a handy last-minute stop for flowers, ice or forgotten essentials on the morning of the wedding.",
      neighbours:["raby","minto","eschol-park","kearns"] },

    { slug:"eschol-park", name:"Eschol Park", postcode:"2558", region:"macarthur",
      lead:"Eschol Park is a quiet, green suburb well suited to intimate at-home ceremonies.",
      about:"Eschol Park is a small, peaceful residential pocket bordered by reserves and open space, giving it a calm, tucked-away feel. It's the kind of place where couples marry surrounded by family in a familiar garden.",
      ceremony:"Small backyard and reserve ceremonies are the norm in Eschol Park. I keep everything relaxed and warm, look after the paperwork, and bring the equipment needed to make even a modest setting feel special.",
      venues:[{name:"Family backyards",note:"the heart of most Eschol Park weddings"},{name:"Neighbourhood reserves",note:"green space for an outdoor exchange"},{name:"Nearby Eagle Vale venues",note:"an easy option for the reception"}],
      tip:"For a small ceremony, seating even a dozen guests in a semi-circle makes the moment feel intimate and helps everyone see and hear your vows.",
      neighbours:["eagle-vale","kearns","st-andrews","raby"] },

    { slug:"st-andrews", name:"St Andrews", postcode:"2566", region:"macarthur",
      lead:"St Andrews offers established gardens and easy access for a comfortable family wedding.",
      about:"St Andrews is a mature residential suburb with leafy streets, a local golf course and well-kept gardens. Its settled character and central Macarthur location make it convenient for couples and their guests alike.",
      ceremony:"Home and reserve ceremonies suit St Andrews, often with a golf-club or nearby venue reception. I take care of the legal side and craft a ceremony that reflects your story, whatever the setting.",
      venues:[{name:"Golf-course & club venues",note:"green outlooks and full facilities"},{name:"Established backyards",note:"mature gardens for a natural ceremony"},{name:"Local reserves",note:"open, accessible outdoor spaces"}],
      tip:"If you're eyeing a golf-club setting, check their ceremony times around member play — I'll happily liaise with the venue so it all runs smoothly.",
      neighbours:["raby","eschol-park","kearns","macquarie-fields"] },

    { slug:"kearns", name:"Kearns", postcode:"2558", region:"macarthur",
      lead:"Kearns is a quiet, tightly-knit suburb ideal for close, personal ceremonies.",
      about:"Kearns is a compact residential suburb with a strong neighbourhood feel, ringed by parks and close to the amenities of Eagle Vale and Eschol Park. It's a settled, friendly pocket where many couples have deep local roots.",
      ceremony:"Intimate backyard and park ceremonies are typical in Kearns. I make the day feel personal and unhurried, and manage all the legal requirements from your Notice of Intended Marriage onward.",
      venues:[{name:"Local parks",note:"green settings within walking distance for many"},{name:"Family backyards",note:"warm, familiar ceremony spaces"},{name:"Nearby Eagle Vale amenities",note:"convenient for guests and catering"}],
      tip:"In a close community like Kearns, an early rehearsal walk-through helps nervous family members feel confident about their part on the day.",
      neighbours:["eagle-vale","eschol-park","raby","st-andrews"] },

    { slug:"macquarie-links", name:"Macquarie Links", postcode:"2565", region:"macarthur",
      lead:"Macquarie Links is my home base, so a ceremony here is quite literally on my doorstep — and its championship golf setting brings a touch of resort-style elegance.",
      about:"Macquarie Links is a planned estate built around a championship golf course, giving it a manicured, upmarket feel that's unusual for the area. Its landscaped surrounds and clubhouse make it a natural choice for couples wanting a polished garden or club-style wedding close to Macquarie Fields.",
      ceremony:"Many couples here marry on manicured lawns or at the clubhouse, with the reception following on-site. Because I am based right here, I can meet you easily and arrive early; I coordinate with the venue and keep the ceremony elegant, warm and perfectly timed.",
      venues:[{name:"Golf-club lawns & clubhouse",note:"manicured, photogenic ceremony-and-reception settings"},{name:"Estate gardens",note:"landscaped greenery for outdoor vows"},{name:"Private residences",note:"refined at-home ceremonies within the estate"}],
      tip:"Golf-course estates look their best in late afternoon light — ask your photographer and I about timing your ceremony for that golden-hour glow.",
      neighbours:["ingleburn","glenfield","macquarie-fields"] },

    { slug:"denham-court", name:"Denham Court", postcode:"2565", region:"macarthur",
      lead:"Denham Court's semi-rural pockets and estate homes lend themselves to spacious garden weddings.",
      about:"Denham Court blends established semi-rural properties with newer estate development, giving it larger blocks and a green, open character. That space makes it a lovely spot for garden ceremonies where families can spread out and children can roam.",
      ceremony:"Property and backyard ceremonies suit Denham Court, often on generous grounds. I bring a full PA to carry your vows across the space and manage all the legal formalities with care.",
      venues:[{name:"Semi-rural properties",note:"expansive grounds for a garden wedding"},{name:"Estate backyards",note:"modern, landscaped outdoor settings"},{name:"Nearby Edmondson Park venues",note:"handy for the reception"}],
      tip:"On larger Denham Court properties, think about where cars will park and how guests reach the ceremony spot — a little signage saves confusion on the day.",
      neighbours:["ingleburn","edmondson-park","leppington","bow-bowing"] },

    { slug:"bow-bowing", name:"Bow Bowing", postcode:"2566", region:"macarthur",
      lead:"Bow Bowing is a small, convenient suburb close to Minto and Ingleburn's amenities.",
      about:"Bow Bowing is a compact residential suburb wedged between Minto and Ingleburn, with easy access to their shops, stations and reserves. Its central location makes it a practical base for a wedding that draws guests from across the Macarthur region.",
      ceremony:"Ceremonies in Bow Bowing are usually held at home or at nearby reserves, with the reception a short drive away. I take care of the paperwork and shape a ceremony that suits your style and setting.",
      venues:[{name:"Family backyards",note:"intimate, close-to-home ceremonies"},{name:"Nearby Minto & Ingleburn reserves",note:"green outdoor options minutes away"},{name:"Local community venues",note:"a weatherproof backup"}],
      tip:"With Minto and Ingleburn stations both close by, Bow Bowing is easy for train guests — note the nearer station on your invitations.",
      neighbours:["minto","ingleburn"] },

    // ---------------- CAMDEN & SW GROWTH ----------------
    { slug:"camden", name:"Camden", postcode:"2570", region:"camden",
      lead:"Historic Camden delivers that romantic, country-but-close-to-the-city wedding feel like nowhere else in the South West.",
      about:"Camden is one of Sydney's most picturesque historic towns, with heritage streetscapes, surrounding farmland and established garden estates that give weddings a genuine country-romance atmosphere just an hour from the city. It's a perennial favourite for couples wanting elegance, greenery and a sense of occasion.",
      ceremony:"Camden couples often marry at a homestead, winery-style venue or garden estate, with the ceremony and reception on the same grounds. I know the area's rhythm well and keep your ceremony warm, polished and beautifully timed for the light.",
      venues:[{name:"Historic homesteads & estates",note:"heritage grounds and manicured gardens"},{name:"Garden & winery-style venues",note:"country elegance with established trees"},{name:"Camden's heritage precinct",note:"charming backdrops for photos"}],
      tip:"Camden's best garden venues book out a year or more ahead for spring and autumn Saturdays — lock in your date and celebrant early.",
      neighbours:["narellan","elderslie","currans-hill","spring-farm"] },

    { slug:"narellan", name:"Narellan", postcode:"2567", region:"camden",
      lead:"Narellan combines modern amenities with proximity to Camden's celebrated garden venues.",
      about:"Narellan is a busy commercial hub for the Camden district, with contemporary shopping, dining and reception facilities alongside quick access to the area's historic garden venues. It's a practical, well-serviced base that keeps everything a couple needs within easy reach.",
      ceremony:"Couples in Narellan enjoy the best of both worlds — modern function venues in town and garden estates minutes away. I travel easily between them and handle the full ceremony and legalities.",
      venues:[{name:"Modern function centres",note:"contemporary all-in-one wedding venues"},{name:"Nearby Camden estates",note:"garden romance a short drive away"},{name:"Local parks & reserves",note:"green settings for outdoor vows"}],
      tip:"Narellan's town centre gets busy on weekends — if your ceremony is nearby, give guests a clear venue pin and parking note to avoid the shopping-centre crush.",
      neighbours:["camden","harrington-park","currans-hill","oran-park"] },

    { slug:"oran-park", name:"Oran Park", postcode:"2570", region:"camden",
      lead:"Oran Park is one of the South West's fastest-growing communities, full of fresh, modern wedding settings.",
      about:"Oran Park is a thriving master-planned community with new parks, a town centre and contemporary homes, attracting young families and couples building their lives in the region. Its modern estates and landscaped public spaces give weddings a clean, current backdrop.",
      ceremony:"Many Oran Park couples marry in a new estate backyard, a landscaped town park, or a nearby Camden venue. I bring everything needed to make a modern setting feel warm and personal, and I manage the paperwork end to end.",
      venues:[{name:"Landscaped town parks",note:"modern, well-kept public green spaces"},{name:"New estate backyards",note:"contemporary outdoor ceremony settings"},{name:"Nearby Camden & Narellan venues",note:"garden and function options close by"}],
      tip:"Oran Park's newer parks can be short on mature shade — for a summer ceremony, plan an arbour or marquee, and I'll position guests out of the direct sun.",
      neighbours:["narellan","gregory-hills","harrington-park","leppington"] },

    { slug:"gregory-hills", name:"Gregory Hills", postcode:"2557", region:"camden",
      lead:"Gregory Hills offers bright, modern surrounds and a growing choice of local venues.",
      about:"Gregory Hills is a newer growth suburb with a business park, town centre and contemporary residential estates. Its fresh infrastructure and central position between Camden and Campbelltown make it a convenient, modern choice for couples.",
      ceremony:"Ceremonies here are often held in estate gardens, local parks or nearby function venues. I keep the day relaxed and well-organised, and take care of every legal requirement.",
      venues:[{name:"Estate gardens & parks",note:"modern landscaped outdoor settings"},{name:"Local function venues",note:"contemporary ceremony-and-reception spaces"},{name:"Nearby Gledswood-district estates",note:"garden venues a short drive away"}],
      tip:"Being newer, Gregory Hills addresses aren't always recognised by older GPS units — send guests a dropped map pin rather than just the street name.",
      neighbours:["oran-park","harrington-park","currans-hill"] },

    { slug:"harrington-park", name:"Harrington Park", postcode:"2567", region:"camden",
      lead:"Harrington Park's landscaped lake and gardens make it a standout for photogenic ceremonies.",
      about:"Harrington Park is a well-planned suburb built around a central lake and generous green space, giving it a calm, landscaped elegance. Its manicured surrounds and lakeside reserves are genuinely lovely for outdoor weddings and photography.",
      ceremony:"Lakeside and garden ceremonies are a highlight in Harrington Park, often followed by a reception nearby in Narellan or Camden. I choose the best spot with you and keep the ceremony warm and beautifully paced.",
      venues:[{name:"Harrington Park lake reserves",note:"landscaped, water-touched ceremony settings"},{name:"Estate gardens",note:"manicured greenery for outdoor vows"},{name:"Nearby Narellan venues",note:"handy for the celebration"}],
      tip:"The lakeside reserves are popular on weekends — arrive early to claim your preferred spot, and I'll have everything set before guests arrive.",
      neighbours:["narellan","gregory-hills","oran-park","mount-annan"] },

    { slug:"mount-annan", name:"Mount Annan", postcode:"2567", region:"camden",
      lead:"Mount Annan is home to Australia's largest botanic garden — a spectacular natural backdrop for weddings.",
      about:"Mount Annan is best known for the Australian Botanic Garden, a vast expanse of lawns, wildflower meadows and dramatic plantings that draws couples from across Sydney. The suburb itself is green and family-oriented, with the garden as its crowning natural feature.",
      ceremony:"Many couples marry within or near the botanic garden's sweeping lawns, making the most of the seasonal colour and open space. I'm familiar with garden ceremonies here and coordinate the timing, sound and legalities so nature does the decorating.",
      venues:[{name:"Australian Botanic Garden",note:"expansive lawns and meadows — a signature local setting"},{name:"Estate backyards",note:"green, spacious at-home ceremonies"},{name:"Nearby Camden venues",note:"garden receptions minutes away"}],
      tip:"Public gardens require a booking or permit for weddings — sort that early, and I'll help you understand what the garden allows for chairs, arbours and guest numbers.",
      neighbours:["currans-hill","harrington-park","spring-farm"] },

    { slug:"currans-hill", name:"Currans Hill", postcode:"2567", region:"camden",
      lead:"Currans Hill offers elevated outlooks and quick access to Camden and Narellan's venues.",
      about:"Currans Hill is a residential suburb on rising ground near Narellan, with pleasant outlooks across the Camden valley and a settled, family feel. Its position keeps couples close to the district's garden venues and modern amenities.",
      ceremony:"Home and reserve ceremonies suit Currans Hill, with receptions typically in Narellan or Camden. I visit beforehand to find the best outlook for your vows and handle all the legal details.",
      venues:[{name:"Elevated backyard ceremonies",note:"valley outlooks for memorable photos"},{name:"Local reserves",note:"green, open settings"},{name:"Nearby Camden & Narellan venues",note:"a short drive for the reception"}],
      tip:"Currans Hill's higher blocks can be breezy — I'll site your ceremony to shelter guests and keep candles and light décor from blowing about.",
      neighbours:["narellan","mount-annan","camden","gregory-hills"] },

    { slug:"elderslie", name:"Elderslie", postcode:"2570", region:"camden",
      lead:"Elderslie sits on the Nepean's edge, blending riverside greenery with Camden's historic charm.",
      about:"Elderslie is a leafy suburb bordering Camden and the Nepean River, with established homes, river reserves and a genuine sense of the area's rural heritage. Its greenery and proximity to Camden's estates make it a picturesque wedding base.",
      ceremony:"Riverside and garden ceremonies suit Elderslie, often flowing into a reception at a nearby Camden venue. I keep the ceremony personal and warm, and take care of every legal step.",
      venues:[{name:"Nepean River reserves",note:"tranquil, water-touched outdoor settings"},{name:"Established garden backyards",note:"mature greenery for a natural ceremony"},{name:"Nearby Camden estates",note:"heritage venues close at hand"}],
      tip:"River reserves can be soft underfoot after rain — I'll check the ground and, if needed, help you choose a firmer spot so heels and wheelchairs aren't caught out.",
      neighbours:["camden","spring-farm","narellan"] },

    { slug:"spring-farm", name:"Spring Farm", postcode:"2570", region:"camden",
      lead:"Spring Farm is a fresh, family-focused estate suburb close to Camden and Mount Annan.",
      about:"Spring Farm is a newer residential community on Camden's southern edge, with modern homes, parks and easy access to both Camden's historic venues and Mount Annan's botanic garden. Its contemporary estates suit couples wanting a clean, current setting.",
      ceremony:"Estate backyard and park ceremonies are common in Spring Farm, with receptions in Camden or nearby. I bring the equipment and calm coordination to make a modern setting feel special, and manage the legalities throughout.",
      venues:[{name:"Estate parks & backyards",note:"modern landscaped ceremony spaces"},{name:"Nearby Mount Annan garden",note:"a spectacular natural option minutes away"},{name:"Camden venues",note:"historic charm for the celebration"}],
      tip:"As a newer estate, Spring Farm's trees are still young — plan for shade at a summer ceremony, and I'll arrange seating to keep guests comfortable.",
      neighbours:["camden","elderslie","mount-annan","rosemeadow"] },

    { slug:"rosemeadow", name:"Rosemeadow", postcode:"2560", region:"camden",
      lead:"Rosemeadow blends bushland surrounds with an easy link between Campbelltown and Camden.",
      about:"Rosemeadow is a green, established suburb bordered by bushland reserves, sitting between Campbelltown and the Camden growth corridor. Its natural surrounds and settled community give weddings a relaxed, unfussy character.",
      ceremony:"Backyard and reserve ceremonies suit Rosemeadow, with receptions a short drive in either direction. I shape the ceremony to your setting and handle the legal side from the outset.",
      venues:[{name:"Bushland reserves",note:"natural green backdrops on the suburb's edge"},{name:"Family backyards",note:"intimate, close-to-home ceremonies"},{name:"Nearby Campbelltown & Camden venues",note:"flexible reception options"}],
      tip:"Rosemeadow's bush edges are lovely but watch for uneven ground and afternoon insects near dusk — I'll help you pick a time and spot that keeps guests comfortable.",
      neighbours:["ambarvale","bradbury","spring-farm"] },

    // ---------------- LIVERPOOL & SURROUNDS ----------------
    { slug:"liverpool", name:"Liverpool", postcode:"2170", region:"liverpool",
      lead:"Liverpool is one of Sydney's most vibrant, multicultural cities — a wonderful place for a ceremony that celebrates two cultures.",
      about:"Liverpool is a major regional centre in South West Sydney, rich in cultural diversity with a bustling city heart, riverside parklands along the Georges River, and a full range of function venues. Its multicultural community means many of the weddings I conduct here joyfully blend traditions, faiths and languages.",
      ceremony:"Liverpool couples often marry at riverside reserves, city function venues or family homes, with a strong love of ceremonies that honour heritage. I specialise in cross-cultural and bilingual ceremonies — including Christian blessings and Hindi elements — so every guest feels included.",
      venues:[{name:"Georges River parklands",note:"green, riverside ceremony settings in the city's heart"},{name:"City function & reception venues",note:"well-equipped for large, multicultural celebrations"},{name:"Family homes",note:"personal ceremonies rich in tradition"}],
      tip:"For a large multicultural wedding, a short rehearsal helps everyone — including relatives performing cultural rites — feel confident about the running order on the day.",
      neighbours:["casula","moorebank","prestons","chipping-norton"] },

    { slug:"casula", name:"Casula", postcode:"2170", region:"liverpool",
      lead:"Casula pairs riverside greenery with the arts and dining of the Powerhouse precinct.",
      about:"Casula sits on the Georges River just south of Liverpool, home to the Casula Powerhouse Arts Centre and green riverside reserves. Its blend of culture, parkland and diverse community gives couples a characterful, well-connected setting.",
      ceremony:"Riverside and reserve ceremonies suit Casula, often with the reception nearby in Liverpool. I handle the full ceremony and legalities and can weave in the cultural elements so many local couples want.",
      venues:[{name:"Casula riverside reserves",note:"leafy, water-touched outdoor settings"},{name:"Powerhouse precinct surrounds",note:"a cultural, characterful backdrop"},{name:"Nearby Liverpool venues",note:"full-service reception options"}],
      tip:"The riverside reserves are popular for picnics on weekends — arriving early secures your spot and lets me set up in peace before guests arrive.",
      neighbours:["liverpool","glenfield","prestons","wattle-grove"] },

    { slug:"prestons", name:"Prestons", postcode:"2170", region:"liverpool",
      lead:"Prestons is a growing, diverse suburb with modern homes and convenient local venues.",
      about:"Prestons is a rapidly developing suburb west of Liverpool, with new residential estates, parks and a culturally diverse community. Its modern homes and open spaces make it an easy, welcoming place for a contemporary wedding.",
      ceremony:"Backyard and park ceremonies are common in Prestons, with receptions in Liverpool nearby. I bring everything needed for a polished ceremony and take care of the legal requirements from your NOIM onward.",
      venues:[{name:"Local parks",note:"modern green spaces for outdoor vows"},{name:"Estate backyards",note:"contemporary at-home ceremony settings"},{name:"Nearby Liverpool venues",note:"handy for the celebration"}],
      tip:"Prestons is still growing, so double-check your venue's exact entrance — new estates can have multiple access roads that confuse first-time visitors.",
      neighbours:["casula","liverpool","edmondson-park","glenfield"] },

    { slug:"edmondson-park", name:"Edmondson Park", postcode:"2174", region:"liverpool",
      lead:"Edmondson Park is a fresh, transit-connected community with modern parks and gathering spaces.",
      about:"Edmondson Park is a newer master-planned suburb built around its railway station and town centre, with landscaped parks and contemporary homes. Its transport links make it especially easy for guests travelling from across Sydney.",
      ceremony:"Couples here often marry in a landscaped park, a new estate backyard, or a nearby venue. I keep the ceremony warm and well-timed, and manage the paperwork so nothing legal is left to chance.",
      venues:[{name:"Landscaped town parks",note:"modern, well-kept public green spaces"},{name:"New estate backyards",note:"clean, contemporary ceremony settings"},{name:"Nearby Liverpool & Leppington venues",note:"flexible reception options"}],
      tip:"Edmondson Park station sits at the suburb's heart — a genuinely handy meeting point for guests catching the train rather than driving.",
      neighbours:["prestons","leppington","denham-court","ingleburn"] },

    { slug:"leppington", name:"Leppington", postcode:"2179", region:"liverpool",
      lead:"Leppington's semi-rural blocks offer space and greenery for a relaxed country-style wedding.",
      about:"Leppington sits in the South West growth corridor, keeping much of its semi-rural character with larger properties and open paddocks even as new development arrives. That space gives couples room for a genuine garden or property wedding.",
      ceremony:"Property and backyard ceremonies suit Leppington's larger blocks, often with a marquee reception on the same grounds. I bring a full PA to carry your vows across open space and handle all the legalities.",
      venues:[{name:"Semi-rural properties",note:"expansive grounds for a country-style wedding"},{name:"Estate backyards",note:"newer landscaped ceremony settings"},{name:"Nearby Oran Park & Edmondson Park venues",note:"convenient reception options"}],
      tip:"On rural Leppington blocks, plan for parking on grass and let guests know — flat shoes for the walk in, then heels for the ceremony, is my usual advice.",
      neighbours:["edmondson-park","oran-park","denham-court"] },

    { slug:"moorebank", name:"Moorebank", postcode:"2170", region:"liverpool",
      lead:"Moorebank enjoys a peaceful riverside setting between the Georges River and Liverpool.",
      about:"Moorebank sits in a bend of the Georges River just east of Liverpool, with riverside reserves, established homes and a quiet, green character. Its water frontage and leafy streets make it a calm, attractive setting for outdoor ceremonies.",
      ceremony:"Riverside and backyard ceremonies suit Moorebank, with receptions in Liverpool close by. I choose the best riverside spot with you and take care of the ceremony and all legal steps.",
      venues:[{name:"Georges River reserves",note:"tranquil, water-touched ceremony settings"},{name:"Established backyards",note:"leafy, private at-home ceremonies"},{name:"Nearby Liverpool venues",note:"a short hop for the celebration"}],
      tip:"River reserves near Moorebank can flood-affect after heavy rain — I keep an eye on conditions and we'll have a simple backup plan ready just in case.",
      neighbours:["liverpool","chipping-norton","wattle-grove","holsworthy"] },

    { slug:"chipping-norton", name:"Chipping Norton", postcode:"2170", region:"liverpool",
      lead:"Chipping Norton's lakes and river frontage make it one of the area's prettiest waterside wedding spots.",
      about:"Chipping Norton is defined by its lakes and the Georges River, with waterfront reserves, rowing waters and green foreshores that give it a distinctly scenic, relaxed feel. Those water views are a real drawcard for outdoor ceremonies.",
      ceremony:"Lakeside and foreshore ceremonies shine in Chipping Norton, often followed by a reception nearby in Liverpool. I set up so your vows carry across the water setting and handle every legal detail.",
      venues:[{name:"Chipping Norton Lakes foreshore",note:"scenic waterside ceremony settings"},{name:"Georges River reserves",note:"green, water-touched outdoor spaces"},{name:"Nearby Liverpool venues",note:"full-service reception options"}],
      tip:"Waterside spots can be breezy in the afternoon — I'll site your ceremony with the wind behind the microphone so every word carries clearly.",
      neighbours:["moorebank","liverpool","hammondville"] },

    { slug:"hammondville", name:"Hammondville", postcode:"2170", region:"liverpool",
      lead:"Hammondville is a quiet, green riverside pocket ideal for intimate ceremonies.",
      about:"Hammondville is a small, settled suburb near the Georges River, with parks, a strong community heritage and a peaceful residential feel. Its modest scale and greenery suit couples wanting a low-key, personal wedding close to home.",
      ceremony:"Backyard and riverside reserve ceremonies suit Hammondville, with receptions in nearby Liverpool or Moorebank. I keep the day warm and unhurried and manage all the legal requirements.",
      venues:[{name:"Local river reserves",note:"green, quiet outdoor ceremony spots"},{name:"Family backyards",note:"intimate, close-to-home settings"},{name:"Nearby Moorebank & Liverpool venues",note:"easy reception options"}],
      tip:"For an intimate Hammondville ceremony, a small semicircle of chairs close to the couple keeps the moment warm and lets everyone hear the vows.",
      neighbours:["chipping-norton","wattle-grove","holsworthy"] },

    { slug:"wattle-grove", name:"Wattle Grove", postcode:"2173", region:"liverpool",
      lead:"Wattle Grove offers a leafy, well-planned setting with a strong family community.",
      about:"Wattle Grove is a tidy, established suburb known for its tree-lined streets, local lake reserve and community-minded feel. Its greenery and calm layout make it a comfortable, attractive base for a relaxed wedding.",
      ceremony:"Reserve and backyard ceremonies suit Wattle Grove, with receptions nearby in Liverpool or the Georges River area. I take care of the ceremony and legalities and help you choose the greenest spot.",
      venues:[{name:"Wattle Grove lake reserve",note:"leafy, water-touched ceremony settings"},{name:"Established backyards",note:"tree-lined, private at-home ceremonies"},{name:"Nearby Liverpool venues",note:"handy for the celebration"}],
      tip:"The lake reserve is a local favourite for family gatherings — booking ahead where required keeps your ceremony spot clear on the day.",
      neighbours:["casula","moorebank","holsworthy","hammondville"] },

    { slug:"holsworthy", name:"Holsworthy", postcode:"2173", region:"liverpool",
      lead:"Holsworthy bridges the Liverpool district and the Georges River bushland to the south.",
      about:"Holsworthy is a settled residential suburb bordered by extensive bushland and the Georges River, with its own railway station and a quiet, green character. Its position links the Liverpool area to the Menai district across the river.",
      ceremony:"Backyard and reserve ceremonies suit Holsworthy, with receptions in Liverpool or across toward Menai. I handle the ceremony and legal steps and bring the equipment to make any setting shine.",
      venues:[{name:"Bushland-edge reserves",note:"natural green ceremony backdrops"},{name:"Family backyards",note:"private, personal at-home settings"},{name:"Nearby Liverpool & Menai venues",note:"reception options on either side of the river"}],
      tip:"Holsworthy station makes train travel easy for guests — and if your ceremony is near the bush edge, remind them to bring flat shoes for any unpaved paths.",
      neighbours:["wattle-grove","moorebank","hammondville","menai"] },

    // ---------------- GEORGES RIVER & MENAI ----------------
    { slug:"menai", name:"Menai", postcode:"2234", region:"georges",
      lead:"Menai's leafy bushland setting is perfect for intimate, nature-framed ceremonies.",
      about:"Menai sits on a bush-fringed plateau above the Georges River, with a village-style town centre, national park nearby and a calm, green character that feels a world away from the suburbs. Its natural surrounds make it a favourite for relaxed, intimate weddings.",
      ceremony:"Bushland reserve and backyard ceremonies suit Menai, often small and personal, with receptions at local clubs. I keep the ceremony warm and unhurried and take care of every legal requirement.",
      venues:[{name:"Bushland reserves",note:"natural, secluded ceremony settings"},{name:"Local clubs",note:"comfortable, weatherproof celebration spaces"},{name:"Family backyards",note:"intimate, leafy at-home ceremonies"}],
      tip:"Menai's bush settings are gorgeous but can be warm and buggy at dusk in summer — a late-afternoon ceremony with light repellent on hand keeps everyone comfortable.",
      neighbours:["illawong","bangor","alfords-point","holsworthy"] },

    { slug:"illawong", name:"Illawong", postcode:"2234", region:"georges",
      lead:"Illawong's riverside greenery and outlooks make for genuinely beautiful ceremony settings.",
      about:"Illawong occupies a leafy peninsula bounded by the Georges and Woronora Rivers, with larger blocks, water outlooks and a peaceful, green feel. Its riverside character and established gardens lend themselves to relaxed, scenic weddings.",
      ceremony:"Backyard and riverside ceremonies suit Illawong, often on properties with water views. I visit beforehand to find the best outlook for your vows and handle the ceremony and legalities.",
      venues:[{name:"Riverside reserves",note:"water outlooks for memorable ceremony photos"},{name:"Established garden backyards",note:"leafy, private at-home settings"},{name:"Nearby Menai venues",note:"handy for the reception"}],
      tip:"Illawong's water-view blocks can be steep — I'll help you choose a level spot for the ceremony so guests and the arbour sit comfortably.",
      neighbours:["menai","alfords-point","padstow"] },

    { slug:"alfords-point", name:"Alfords Point", postcode:"2234", region:"georges",
      lead:"Alfords Point offers quiet riverside charm at the edge of the Menai district.",
      about:"Alfords Point is a small, leafy suburb on the Georges River, connected to the Padstow side by its landmark bridge. Its riverside reserves and calm streets give it a tranquil, green character well suited to intimate ceremonies.",
      ceremony:"Riverside reserve and backyard ceremonies suit Alfords Point, with receptions across the river or in the Menai area. I keep everything relaxed and personal and manage all the legal steps.",
      venues:[{name:"Georges River reserves",note:"tranquil, water-touched ceremony settings"},{name:"Family backyards",note:"quiet, leafy at-home ceremonies"},{name:"Nearby Menai & Padstow venues",note:"reception options on both riverbanks"}],
      tip:"Riverside reserves here are peaceful on weekday evenings — worth considering if you'd love water views without weekend crowds.",
      neighbours:["menai","illawong","padstow"] },

    { slug:"revesby", name:"Revesby", postcode:"2212", region:"georges",
      lead:"Revesby combines a lively town centre with green reserves and a strong community spirit.",
      about:"Revesby is a well-established suburb south of the Georges River, with a busy shopping strip, its own station and a large workers' club, alongside leafy parks and a diverse, community-minded population. It's a practical, welcoming base for a wedding.",
      ceremony:"Reserve, club and backyard ceremonies all suit Revesby, with the club and local venues popular for combined ceremony-and-reception days. I coordinate with venues and handle the full ceremony and legalities.",
      venues:[{name:"Workers' & community clubs",note:"spacious, weatherproof all-in-one venues"},{name:"Local parks & reserves",note:"green outdoor ceremony settings"},{name:"Family backyards",note:"personal at-home ceremonies"}],
      tip:"Revesby station and the club are central landmarks — using them as your reference point makes directions simple for guests coming by train or car.",
      neighbours:["padstow","panania","picnic-point"] },

    { slug:"padstow", name:"Padstow", postcode:"2211", region:"georges",
      lead:"Padstow offers riverside reserves and easy access on the southern side of the Georges River.",
      about:"Padstow is a settled suburb near the Georges River, with parks, a busy local centre and a bridge link across to the Menai district. Its riverside reserves and convenient transport make it an easy, green choice for couples.",
      ceremony:"Riverside and backyard ceremonies suit Padstow, with receptions at local venues or across the river. I take care of the ceremony and legal requirements and help you pick the loveliest riverside spot.",
      venues:[{name:"Georges River foreshore reserves",note:"green, water-touched ceremony settings"},{name:"Local parks",note:"accessible outdoor ceremony spaces"},{name:"Nearby clubs & venues",note:"comfortable reception options"}],
      tip:"The Alfords Point Bridge links Padstow to the Menai side in minutes — handy if your ceremony and reception sit on opposite riverbanks.",
      neighbours:["revesby","panania","alfords-point","illawong"] },

    { slug:"panania", name:"Panania", postcode:"2213", region:"georges",
      lead:"Panania is a friendly, green suburb with riverside parks close at hand.",
      about:"Panania is a comfortable residential suburb near the Georges River, with local shops, its own station and easy access to riverside reserves. Its quiet streets and community feel make it a relaxed, unpretentious wedding base.",
      ceremony:"Backyard and riverside reserve ceremonies suit Panania, with receptions in nearby Revesby or Padstow. I keep the ceremony warm and personal and manage all the legal steps.",
      venues:[{name:"Riverside reserves",note:"green, water-touched outdoor settings"},{name:"Family backyards",note:"intimate at-home ceremonies"},{name:"Nearby Revesby venues",note:"handy for the celebration"}],
      tip:"Panania's riverside spots are lovely in the morning light — an earlier ceremony can mean softer photos and cooler, calmer conditions in summer.",
      neighbours:["revesby","padstow","picnic-point"] },

    { slug:"picnic-point", name:"Picnic Point", postcode:"2213", region:"georges",
      lead:"Picnic Point lives up to its name, with some of the district's best riverside settings for a wedding.",
      about:"Picnic Point sits right on the Georges River, framed by foreshore reserves, boat ramps and leafy parks that have long made it a favourite spot to gather by the water. Those river views are a genuine highlight for outdoor ceremonies.",
      ceremony:"Riverside reserve ceremonies are the star in Picnic Point, often with a reception nearby in Revesby or Panania. I set up so your vows carry across the open riverside and handle every legal detail.",
      venues:[{name:"Picnic Point foreshore reserves",note:"scenic riverside ceremony settings"},{name:"Riverside parks",note:"green, water-touched outdoor spaces"},{name:"Nearby Revesby & Panania venues",note:"convenient reception options"}],
      tip:"Popular riverside reserves fill up on fine weekends — check whether your spot needs a booking, and arrive early so I can set up before the crowds.",
      neighbours:["panania","revesby","padstow"] },

    { slug:"bangor", name:"Bangor", postcode:"2234", region:"georges",
      lead:"Bangor's bush-fringed streets offer a calm, natural backdrop at the edge of the Menai district.",
      about:"Bangor is a leafy residential suburb bordered by national park bushland, with a quiet, green character and outlooks toward the surrounding reserves. Its natural setting suits couples wanting a relaxed, nature-framed wedding close to Menai.",
      ceremony:"Backyard and bushland reserve ceremonies suit Bangor, with receptions at nearby Menai clubs. I keep the day unhurried and warm and take care of all the legal requirements.",
      venues:[{name:"Bushland-edge reserves",note:"natural, secluded ceremony backdrops"},{name:"Family backyards",note:"leafy, private at-home ceremonies"},{name:"Nearby Menai venues",note:"comfortable reception options"}],
      tip:"Bangor backs onto national park, so evening ceremonies can attract insects — a late-afternoon start and a little repellent keeps guests comfortable.",
      neighbours:["menai","illawong"] }
  ]
};
